### PR TITLE
EO Collections release v. 0.0.5

### PR DESCRIPTION
**Pull request by Graur**

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 Can you start this Github check? Looks like it needs your approval first

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 Sorry, it was my mistake. Now it works

**Comment by Graur** [comment]
@yegor256 Wait a bit please, I found a new type of error with parentheses. I want to fix it, too

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Review by yegor256 — COMMENTED** [review]
looks good

**Review by yegor256 — APPROVED** [review]
good!

**Pull request merged**
