### PR TITLE
added auto-pull script

### PR DESCRIPTION
**Pull request by Graur**
Closes: #137

---

## PR-Codex overview
This PR automates the process of checking for new releases of dependencies and updating them. 

### Detailed summary
- Added a GitHub workflow to check for new releases
- Created a Python script to automate the process of checking for new releases and updating dependencies
- Uses the `requests` library to query the GitHub API for the latest release of each dependency
- Automatically creates a pull request with the updated dependencies

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by yegor256** [comment]
@Graur can you get rid of the `releases.txt` file and just use the information we already have in this repository, see: https://github.com/objectionary/home/blob/master/objects/org/eolang/collections/hash-code-of.eo#L26 ?

**Comment by Graur** [comment]
Maybe we need to create a new release with some tag

**Comment by yegor256** [comment]
@Graur fixed, try again: https://github.com/objectionary/eo-math/releases/tag/0.4.0

**Comment by Graur** [comment]
@yegor256 Now it's good, thanks!

**Comment by yegor256** [comment]
@Graur ready to merge?

**Comment by Graur** [comment]
@yegor256 Yes, let's try to merge

**Review by yegor256 — APPROVED** [review]
ok

**Comment by yegor256** [comment]
@Graur done

**Comment by Graur** [comment]
@yegor256 Thanks!

**Pull request merged**
