### PR TITLE
Removed deprecated syntax in releases workflow

### PR DESCRIPTION
**Pull request by Graur**
#141

---

## PR-Codex overview

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 I updated `auto-pull.py` script to use `GITHUB_ENV` between Actions steps. And I removed deprecated syntax from Github Actions according to [GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). Please have a look

**Comment by Graur** [comment]
@yegor256 Reminder

**Review by yegor256 — APPROVED** [review]
ok

**Comment by yegor256** [comment]
@Graur thanks

**Pull request merged**
