### PR TITLE
EO Collections version was up to 0.0.6

### PR DESCRIPTION
**Pull request by Graur**
What's done in release:

- removed all redundant parenthesis from eo-collections block. So, now we can update other repositories to newest version and set their `failOnwarning` flags to `true`

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 please, have a look

**Comment by Graur** [comment]
@yegor256 Can you please take a look, since this pull request blocks several releases: `eo-math`, `eo-strings` and `eo-hamcrest` (with fail on redundant parenthesis)

**Review by yegor256 — APPROVED** [review]
ok

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 Thanks!

**Pull request merged**
