### PR TITLE
Update EO to 0.36.0

### PR DESCRIPTION
**Pull request by maxonfjvipon**
## PR-Codex overview
This PR updates the version to 0.36.0, changes package names, and improves object documentation and metadata.

### Detailed summary
- Updated version to 0.36.0
- Changed package names
- Improved object documentation and metadata

> The following files were skipped due to too many changes: `objects/org/eolang/switch.eo`, `objects/org/eolang/memory.eo`, `objects/org/eolang/tuple.eo`, `tests/org/eolang/tuple-tests.eo`, `tests/org/eolang/goto-tests.eo`, `tests/org/eolang/io/tupled-stdout-test.eo`, `tests/org/eolang/try-tests.eo`, `objects/org/eolang/cage.eo`, `objects/org/eolang/goto.eo`, `tests/org/eolang/io/tupled-stdout.eo`, `pom.sh`, `tests/org/eolang/float-tests.eo`, `tests/org/eolang/seq-tests.eo`, `tests/org/eolang/nan-tests.eo`, `tests/org/eolang/int-tests.eo`, `tests/org/eolang/bool-tests.eo`, `objects/org/eolang/negative-infinity.eo`, `tests/org/eolang/malloc-tests.eo`, `objects/org/eolang/positive-infinity.eo`, `tests/org/eolang/memory-tests.eo`, `tests/org/eolang/cage-tests.eo`, `tests/org/eolang/rust-tests.eo`, `tests/org/eolang/while-tests.eo`, `tests/org/eolang/runtime-tests.eo`, `tests/org/eolang/negative-infinity-tests.eo`, `tests/org/eolang/positive-infinity-tests.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
ok

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor status

**Pull request merged**
