### PR TITLE
eo-hamcrest release 0.3.1

### PR DESCRIPTION
**Pull request by mximp**
Releasing `eo-hamcrest v0.3.1` into Objectionary.

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please verify and merge

**Comment by yegor256** [comment]
@mximp please, remove all puzzles from the code. they are not allowed in this repo.

**Comment by mximp** [comment]
> @mximp please, remove all puzzles from the code. they are not allowed in this repo.

@yegor256 done. Please check.

**Comment by yegor256** [comment]
@rultor merge

**Comment by mximp** [comment]
@yegor256 please try again. Fixed the issues.

**Comment by yegor256** [comment]
@rultor merge

**Review by yegor256 — APPROVED** [review]
ok

**Comment by yegor256** [comment]
@mximp your commits are not signed. fix this for the future: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Pull request merged**
