### PR TITLE
publish eo-sys

### PR DESCRIPTION
**Pull request by mximp**

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please merge

**Review by yegor256 — APPROVED** [review]
ok

**Comment by yegor256** [comment]
@mximp please, configure commit signing: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by yegor256** [comment]
@mximp rultor can't merge your PR because your commits are not signed

**Comment by yegor256** [comment]
@rultor merge

**Comment by mximp** [comment]
@yegor256 do you know if I can verify already created commits in PR? Or I have to create new PR?

**Comment by mximp** [comment]
Another PR will be created

**Pull request closed without merging**
