### PR TITLE
EO-Strings version up to 0.1.0

### PR DESCRIPTION
**Pull request by Graur**
What's done:

- EO-string version was up to 0.1.1
- ruby version was up to 3.0

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 Please, wait a bit. I want to figure out what's wrong with this build

**Comment by Graur** [comment]
@yegor256 Can we merge it manually? Because we have some methods in `eo-sys` repository with the old `eo-string` methods. So I suggest to merge this PR and then create fix in `eo-sys` repository.

**Comment by yegor256** [comment]
@Graur what's up with this?

**Comment by Graur** [comment]
@yegor256 It was waiting for `eo-collection` release in #93

**Review by yegor256 — DISMISSED** [review]
ok

**Comment by yegor256** [comment]
@rultor merge

**Pull request closed without merging**
