### PR TITLE
EO release 0.29.0

### PR DESCRIPTION
**Pull request by Graur**

### CODE REVIEW

**Comment by yegor256** [comment]
@Graur the build fails in GHA, please check

**Comment by Graur** [comment]
@yegor256 I updated Ruby version in [workflows/make.yml](https://github.com/objectionary/home/pull/100/files#diff-c619491a91da4d5ad74050f1334ec593c012af3e8d2be4b52539caf2e44ed090) and EO version in pom.xml
Please, take a look again

**Comment by Graur** [comment]
@yegor256 reminder

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 Can you to run it again, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@Graur thanks!

**Pull request merged**
