### PR TITLE
Update EO to 0.40.0

### PR DESCRIPTION
**Pull request by maxonfjvipon**
## PR-Codex overview
This PR primarily updates the `eo` runtime version from `0.39.0` to `0.40.0`, introduces new tests, and modifies various existing tests and implementations to enhance functionality and fix issues.

### Detailed summary
- Updated `eo-runtime` version to `0.40.0` across multiple files.
- Added new tests for various functionalities.
- Modified existing tests for better accuracy and coverage.
- Introduced new objects and improved existing ones for better performance.
- Enhanced error handling in several areas.

> The following files were skipped due to too many changes: `objects/org/eolang/sys/posix.eo`, `objects/org/eolang/bytes.eo`, `objects/org/eolang/txt/text.eo`, `objects/org/eolang/math/integral.eo`, `tests/org/eolang/io/tee-input-tests.eo`, `tests/org/eolang/math/numbers-tests.eo`, `make/jvm/src/main/rust/eo/src/eo_enum.rs`, `objects/org/eolang/math/angle.eo`, `tests/org/eolang/txt/text-tests.eo`, `objects/org/eolang/sys/win32.eo`, `objects/org/eolang/math/real.eo`, `objects/org/eolang/fs/tmpdir.eo`, `tests/org/eolang/math/integral-tests.eo`, `tests/org/eolang/fs/dir-tests.eo`, `objects/org/eolang/io/tee-input.eo`, `objects/org/eolang/i64.eo`, `objects/org/eolang/math/random.eo`, `objects/org/eolang/fs/dir.eo`, `objects/org/eolang/i16.eo`, `tests/org/eolang/i64-tests.eo`, `objects/org/eolang/number.eo`, `objects/org/eolang/i32.eo`, `make/jvm/src/main/rust/eo/src/portal.rs`, `tests/org/eolang/i32-tests.eo`, `tests/org/eolang/i16-tests.eo`, `objects/org/eolang/io/console.eo`, `tests/org/eolang/fs/file-tests.eo`, `tests/org/eolang/fs/path-tests.eo`, `tests/org/eolang/rust-tests.eo`, `objects/org/eolang/fs/file.eo`, `tests/org/eolang/math/real-tests.eo`, `objects/org/eolang/fs/path.eo`, `objects/org/eolang/net/socket.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
LGTM

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 something went wrong

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
