### PR TITLE
eo-math: 0.1.2 release

### PR DESCRIPTION
**Pull request by maxonfjvipon**

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur Could you please clarify what's wrong?

**Comment by Graur** [comment]
@maxonfjvipon Looks like somewhere in this code we use `nan` without `+alias`. Maybe in `number-tests`?

**Comment by maxonfjvipon** [comment]
@Graur you were absolutely right! Many thanks! But there is some `c.eo` object and it can not be found

**Comment by Graur** [comment]
@maxonfjvipon check `number.eo`

**Comment by maxonfjvipon** [comment]
@Graur Oops, my bad, sorry

**Comment by Graur** [comment]
@maxonfjvipon I don't quite understand the problem. Did you make these changes with the `pull.sh` script or just by hand?

**Comment by maxonfjvipon** [comment]
@Graur by hand :D I did not noticed `pull.sh`... Will try it next time, thanks!)

**Comment by Graur** [comment]
@maxonfjvipon You are right, we miss it. Thanks!

**Comment by Graur** [comment]
@maxonfjvipon I think you need to check the `eo-runtime` `math` package again, as the `random` object has changed significantly

**Comment by maxonfjvipon** [comment]
@Graur ok, I'll do it

**Comment by maxonfjvipon** [comment]
@Graur I think that's it

**Comment by Graur** [comment]
@maxonfjvipon Looks good, thanks!
@yegor256 please, have a look

**Comment by yegor256** [comment]
@maxonfjvipon there are some conflicts, please resolve them and we'll merge

**Comment by Graur** [comment]
@maxonfjvipon Maybe it would be better to create a new pull request with help of the pull.sh script?

**Comment by maxonfjvipon** [comment]
@yegor256 It's done, but something is still wrong here with `list`

**Comment by yegor256** [comment]
@maxonfjvipon you should use `org.eolang.collections.list`

**Comment by maxonfjvipon** [comment]
@yegor256 It's done, thanks!

**Comment by yegor256** [comment]
@maxonfjvipon thanks!

**Comment by maxonfjvipon** [comment]
@yegor256 Should I make a PR to `eo-runtime` and remove math objects from there?

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#48](https://github.com/objectionary/home/issues/48) is still not solved.

**Comment by 0pdd** [comment]
@maxonfjvipon the only puzzle [#48](https://github.com/objectionary/home/issues/48) is solved here.

**Pull request merged**
