### PR TITLE
Added workflow for pushing all tags with hashes to gh-pages

### PR DESCRIPTION
**Pull request by yasamprom**
@yegor256 check please

### CODE REVIEW

**Comment by yasamprom** [comment]
Action is triggered by push, pull and pull request. 
It is failed now because `"permission to objectionary/home.git denied to github-actions[bot]"`. 
In fact, it works like [this](https://github.com/yasamprom/home/runs/7543615141?check_suite_focus=true)

**Comment by yegor256** [comment]
@yasamprom merged. let me try to trigger it...

**Comment by yasamprom** [comment]
> @yasamprom merged. let me try to trigger it...

It seems action works like we expected

**Comment by yegor256** [comment]
@yasamprom yes, indeed. cool.

**Pull request merged**
