### PR TITLE
hot fix with 'meta of out order' in eo-hamcrest

### PR DESCRIPTION
**Pull request by Graur**
Related to: https://github.com/objectionary/eo/issues/1620 and https://github.com/objectionary/eo-hamcrest/issues/184

We have some build problem in EO, since eo-hamcrest was released.

What's done:

- hot fix with reordering meta in eo-hamcrest

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 Can you please take a look. It's a hot fix for broken build in EO https://github.com/objectionary/eo/issues/1620

**Comment by yegor256** [comment]
@rultor merge

**Review by yegor256 — APPROVED** [review]
ok

**Comment by yegor256** [comment]
@Graur thanks!

**Pull request merged**
