### PR TITLE
update to 0.39.0

### PR DESCRIPTION
**Pull request by maxonfjvipon**
## PR-Codex overview
The focus of this PR is to update versions and improve testing for the EO language project.

### Detailed summary
- Updated version from 0.38.4 to 0.39.0 in various files
- Added test cases in different test files
- Updated runtime dependencies
- Added new objects and tests

> The following files were skipped due to too many changes: `tests/org/eolang/int-tests.eo`, `objects/org/eolang/tuple.eo`, `objects/org/eolang/malloc.eo`, `objects/org/eolang/while.eo`, `tests/org/eolang/cage-tests.eo`, `tests/org/eolang/while-tests.eo`, `tests/org/eolang/sys/uname-test.eo`, `tests/org/eolang/io/console-tests.eo`, `objects/org/eolang/bytes.eo`, `tests/org/eolang/io/bytes-as-input-test.eo`, `objects/org/eolang/sys/line-separator.eo`, `tests/org/eolang/structs/set-tests.eo`, `tests/org/eolang/structs/bytes-as-array-tests.eo`, `objects/org/eolang/sys/uname.eo`, `tests/org/eolang/io/malloc-as-output-test.eo`, `objects/org/eolang/structs/bytes-as-array.eo`, `objects/org/eolang/txt/sprintf.eo`, `objects/org/eolang/structs/range-of-ints.eo`, `objects/org/eolang/txt/sscanf.eo`, `objects/org/eolang/structs/hash-code-of.eo`, `objects/org/eolang/positive-infinity.eo`, `objects/org/eolang/negative-infinity.eo`, `objects/org/eolang/int.eo`, `tests/org/eolang/structs/range-tests.eo`, `objects/org/eolang/float.eo`, `objects/org/eolang/io/stdin.eo`, `objects/org/eolang/structs/set.eo`, `tests/org/eolang/txt/sprintf-tests.eo`, `objects/org/eolang/structs/range.eo`, `tests/org/eolang/txt/sscanf-tests.eo`, `objects/org/eolang/io/malloc-as-output.eo`, `tests/org/eolang/structs/map-tests.eo`, `objects/org/eolang/io/bytes-as-input.eo`, `tests/org/eolang/structs/hash-code-of-tests.eo`, `tests/org/eolang/bytes-tests.eo`, `objects/org/eolang/structs/map.eo`, `objects/org/eolang/io/console.eo`, `tests/org/eolang/txt/regex-tests.eo`, `objects/org/eolang/txt/regex.eo`, `tests/org/eolang/runtime-tests.eo`, `objects/org/eolang/structs/list.eo`, `tests/org/eolang/txt/text-tests.eo`, `tests/org/eolang/structs/list-tests.eo`, `objects/org/eolang/txt/text.eo`, `tests/org/eolang/rust-tests.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
LGTM

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@maxonfjvipon Hey there! 👋 Great job on your contribution! You've earned +5 points, which is pretty cool considering the scale of your code (5239 hits-of-code!). While we love seeing big changes, remember that [keeping things concise](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) can be super helpful. We noticed only 3 comments on the review – more feedback can really boost the quality. Don't worry though, you're still rocking a [+165](https://www.eolang.org/zerocracy/objectionary-vitals.html) balance! Keep those contributions coming, and let's aim for that sweet spot of code size and review engagement next time. You've got this! 💪

**Comment by 0crat** [comment]
@yegor256 Great job on the review! 🎉 You've scored 55 points: 25 for showing up, a whopping 40 for tackling 5239 hits-of-code, but lost 10 due to only 3 comments. More feedback next time could boost your score even higher! Your total now stands at [+185](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the awesome work!

**Pull request merged**
